- name: clean
  hosts: all
  remote_user: isucon

  tasks:
    - name: chmod log dir and files
      become: yes
      shell: |
        chmod 777 /var/log/{{ app_server }}
        chmod 777 /var/log/{{ database }}
        find /var/log/{{ app_server }}/ -name '*.log' | xargs sudo chmod 666
        find /var/log/{{ database }}/ -name '*.log' | xargs sudo chmod 666

    - name: cleanup log files
      shell: |
        echo "" > /var/log/{{ app_server }}/access.log
        echo "" > /var/log/{{ app_server }}/error.log
        echo "" > /var/log/{{ database }}/access.log
        echo "" > /var/log/{{ database }}/error.log