- name: deploy
  hosts: all
  remote_user: isucon
  tasks:
    - name: pull repository
      shell: |
        git fetch origin
        git checkout $BRANCH
        git pull origin $BRANCH
      args:
        chdir: "{{ repository_root }}"
      environment:
        - BRANCH: "{{ branch }}"

    - name: copy api unit files
      become: true
      copy:
        src: ../configs/isucari.golang.service
        dest: /etc/systemd/system/isucari.golang.service

- hosts: db
  remote_user: isucon
  tasks:
    - name: replace mysql conf
      become: true
      copy:
        src: ../configs/mysql.cnf
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf

    - name: restart mysql
      become: true
      systemd:
        name: mysql.service
        state: restarted
        daemon_reload: yes
        enabled: yes

- hosts: web
  remote_user: isucon
  tasks:
    - name: replace nginx conf
      become: true
      copy:
        src: ../configs/isucari.conf
        dest: /etc/nginx/sites-available/isucari.conf

    - name: restart nginx
      become: true
      systemd:
          name: nginx.service
          state: restarted
          daemon_reload: yes
          enabled: yes

- hosts: api
  remote_user: isucon
  tasks:
    - name: restart service
      become: true
      systemd:
          name: isucari.golang.service
          state: restarted
          daemon_reload: yes
          enabled: yes

    - name: stop mysql
      become: true
      systemd:
        name: mysql.service
        state: stopped
        enabled: no
