- name: deploy
  hosts: all
  remote_user: isucon

  tasks:
    - name: pull repository
      shell: |
        git fetch origin
        git checkout $BRANCH
        git pull origin $BRANCH
      args:
        chdir: "{{ repository_root }}"
      environment:
        - BRANCH: "{{ branch }}"

    # Update configs
    - name: replace nginx conf
      become: true
      copy:
        src: ../configs/isucari.conf
        dest: /etc/nginx/sites-available/isucari.conf

    - name: replace mysql conf
      become: true
      copy:
        src: ../configs/mysql.cnf
        dest: /etc/mysql/conf.d/mysql.cnf

    # Restart service
    - name: restart mysql
      become: true
      systemd:
          name: mysql.service
          state: restarted
          daemon_reload: yes
          enabled: yes

    - name: restart nginx
      become: true
      systemd:
          name: nginx.service
          state: restarted
          daemon_reload: yes
          enabled: yes

    - name: restart service
      become: true
      systemd:
          name: isucari.golang.service
          state: restarted
          daemon_reload: yes
          enabled: yes

