- name: setup-ssh
  hosts: all
  remote_user: root

  vars:
    app_user: isucon
    app_group: isucon

  tasks:
    - name: Ensures .ssh dir exists
      file:
        path: "/home/{{ app_user }}/.ssh/"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        state: directory
        mode: 0775

    - name: ensure authorized_keys file exists
      copy:
        content: ""
        dest: "/home/{{ app_user }}/.ssh/authorized_keys"
        force: no
        group: sys
        owner: "{{ app_user }}"
        mode: 0600

    - name: copy authorized_keys
      copy:
        src: secret/authorized_keys
        dest: /tmp/authorized_keys

    - name: Add authorized_keys
      shell: "cat /tmp/authorized_keys >> /home/{{ app_user }}/.ssh/authorized_keys"
